### ISSUE TITLE
[G2P Connect Demo 1] Configure the benefit calculation

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-demo#5]
Based on the indicators, implement the benefit calculation:
One-time subsidy (up to $100):
- 20$ per child
- 10$ per adult male
- 15$ per adult woman or elderly (over 65)
- 30$ if they have been severely injured

**Comment by gonzalesedwin1123** [comment]
- Added one-time subsidy in g2p_entitlement_cash.
- Prevent total entitlement from exceeding one-time subsidy amount
